 //1
 //0
 //0
 //315
 // 
 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  
 using System.Reflection;
 [assembly: AssemblyCopyright("Copyright © ChrisPulman 2017")]
 [assembly: AssemblyVersion("1.0.315.0")]
 [assembly: AssemblyMetadata("SquirrelAwareVersion", "1")]
 [assembly: AssemblyFileVersion("1.0.315.0")]